services:
  - type: web
    name: pocketbase
    env: docker
    plan: free
    branch: main
    healthCheckPath: /
    startCommand: |
      ./pocketbase superuser upsert admin@example.com myStrongPassword
      ./pocketbase serve --http=0.0.0.0:10000
