services:
  - type: web
    name: pocketbase
    env: docker
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: SUPERUSER_EMAIL
        sync: false
      - key: SUPERUSER_PASSWORD
        sync: false
    startCommand: |
      ./pocketbase superuser upsert "$SUPERUSER_EMAIL" "$SUPERUSER_PASSWORD"
      ./pocketbase serve --http=0.0.0.0:10000
